name: Draw Keymap
on:
  workflow_dispatch:  # allow manual run
  push:
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
      - "keymap_drawer.config.yaml"
      - ".github/workflows/draw.yml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write  # allow pushing the SVG back to the repo
    with:
      keymap_patterns: "config/totem.keymap"        # Which file to parse
      config_path: "keymap_drawer.config.yaml"      # Your config file
      output_folder: "img"                          # Where to save the SVGs
      parse_args: ""                                # Optional: extra parse args